-- AlterTable
ALTER TABLE `cc_char_chat_premium` MODIFY `CHAR_NO` VARCHAR(250) NOT NULL,
    MODIFY `CHAT_ROOM_NO` VARCHAR(250) NOT NULL;

-- AlterTable
ALTER TABLE `cc_user` ADD COLUMN `PREMIUM_CURRENT_ROOM_NO` INTEGER NULL DEFAULT 1,
    ADD COLUMN `PREMIUM_REMEMBER_CONV_COUNT` INTEGER NULL DEFAULT 0;
