-- CreateTable
CREATE TABLE `cc_char` (
    `CHAR_NO` INTEGER NOT NULL AUTO_INCREMENT,
    `CHAR_NAME` VARCHAR(256) NULL,
    `CHAR_TYPE` CHAR(1) NULL DEFAULT 'C',
    `CHAR_INFO` TEXT NULL,
    `UPD_ID` VARCHAR(50) NULL DEFAULT 'admin',
    `UPD_DT` DATETIME(3) NULL,
    `REG_ID` VARCHAR(50) NULL DEFAULT 'admin',
    `REG_DT` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `STD_CODE_NAME` VARCHAR(256) NULL,
    `STD_FULL_NAME` VARCHAR(256) NULL,
    `STD_INC_ID` VARCHAR(256) NULL,
    `STD_ID` BIGINT NULL,
    `STD_TOKEN` VARCHAR(256) NULL,
    `STD_ROLE` BIGINT NULL,
    `STD_ERROR_MSG` VARCHAR(256) NULL DEFAULT '사랑해요.',
    `STD_STATUS` VARCHAR(256) NULL DEFAULT '공부',
    `THUMBNAIL` VARCHAR(256) NULL,
    `TEMPERATURE` DOUBLE NULL DEFAULT 0.5,
    `F_PENALTY` DOUBLE NULL DEFAULT 0.5,
    `P_PENALTY` DOUBLE NULL DEFAULT 0,
    `STD_SHORT_NAME` VARCHAR(20) NULL,

    PRIMARY KEY (`CHAR_NO`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `cc_char_chat` (
    `CHAT_NO` INTEGER NOT NULL AUTO_INCREMENT,
    `CHAR_NO` INTEGER NOT NULL,
    `CHAT_ROOM_NO` INTEGER NOT NULL DEFAULT 1,
    `IS_LEARN` CHAR(1) NULL,
    `REG_DT` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPD_ID` VARCHAR(50) NULL,
    `UPD_DT` DATETIME(3) NULL,
    `CHAT_CONT` TEXT NULL,
    `REG_ID` VARCHAR(50) NULL,

    PRIMARY KEY (`CHAT_NO`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `cc_char_chat_for_learn` (
    `CHAT_LEARN_NO` INTEGER NOT NULL AUTO_INCREMENT,
    `CHAT_CONT` TINYTEXT NULL,
    `REG_ID` VARCHAR(50) NULL,
    `REG_DT` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPD_ID` VARCHAR(50) NULL,
    `UPD_DT` DATETIME(3) NULL,
    `CHAR_NO` INTEGER NOT NULL,
    `CHAT_ROOM_NO` INTEGER NOT NULL DEFAULT 1,

    PRIMARY KEY (`CHAT_LEARN_NO`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `cc_char_chat_log` (
    `CHAT_LOG_NO` INTEGER NOT NULL AUTO_INCREMENT,
    `CHAR_NO` INTEGER NOT NULL,
    `CHAT_ROOM_NO` INTEGER NOT NULL DEFAULT 1,
    `IS_LEARN` CHAR(1) NULL,
    `REG_DT` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPD_ID` VARCHAR(50) NULL DEFAULT 'admin',
    `UPD_DT` DATETIME(3) NULL,
    `CHAT_CONT` TEXT NULL,
    `REG_ID` VARCHAR(50) NULL DEFAULT 'admin',

    PRIMARY KEY (`CHAT_LOG_NO`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `cc_char_chat_premium` (
    `CHAT_NO` INTEGER NOT NULL AUTO_INCREMENT,
    `CHAR_NO` BIGINT NOT NULL,
    `CHAT_ROOM_NO` INTEGER NOT NULL DEFAULT 1,
    `IS_LEARN` CHAR(1) NULL,
    `REG_DT` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPD_ID` VARCHAR(50) NULL,
    `UPD_DT` DATETIME(3) NULL,
    `CHAT_CONT` TEXT NULL,
    `REG_ID` VARCHAR(50) NULL,

    PRIMARY KEY (`CHAT_NO`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `cc_user` (
    `USER_NO` INTEGER NOT NULL AUTO_INCREMENT,
    `USER_NAME` VARCHAR(256) NULL,
    `REG_ID` VARCHAR(50) NULL DEFAULT 'admin',
    `REG_DT` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPD_ID` VARCHAR(50) NULL DEFAULT 'admin',
    `UPD_DT` DATETIME(3) NULL,
    `USER_DISCORD_ID` VARCHAR(256) NULL,
    `TODAY_USER_USAGE` INTEGER NULL DEFAULT 0,

    PRIMARY KEY (`USER_NO`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
